import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#d1c5b4",
        "on-surface": "#e5e2e1",
        "on-error": "#690005",
        "inverse-surface": "#e5e2e1",
        "surface-container-highest": "#353534",
        "surface-container-lowest": "#0e0e0e",
        "inverse-primary": "#775a1a",
        "secondary-fixed": "#ffe088",
        "primary-fixed-dim": "#e9c178",
        "on-primary-container": "#4f3800",
        "secondary-container": "#af8d11",
        secondary: "#e9c349",
        "primary-fixed": "#ffdea5",
        "tertiary-fixed-dim": "#b1c6f9",
        surface: "#131313",
        "on-secondary": "#3c2f00",
        "surface-container-low": "#1c1b1b",
        "on-primary": "#412d00",
        "on-error-container": "#ffdad6",
        "surface-tint": "#e9c178",
        "primary-container": "#c6a15b",
        "tertiary-fixed": "#d8e2ff",
        "surface-container": "#201f1f",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#e9c349",
        "tertiary-container": "#91a6d7",
        "on-tertiary-container": "#253b65",
        "inverse-on-surface": "#313030",
        "on-primary-fixed-variant": "#5d4202",
        "on-primary-fixed": "#271900",
        "on-secondary-fixed": "#241a00",
        "surface-container-high": "#2a2a2a",
        outline: "#9a8f80",
        "surface-bright": "#3a3939",
        background: "#0a0a0a",
        error: "#ffb4ab",
        tertiary: "#b1c6f9",
        "on-secondary-fixed-variant": "#574500",
        "on-tertiary-fixed-variant": "#314671",
        "on-background": "#e5e2e1",
        "on-tertiary-fixed": "#001a42",
        primary: "#c6a15b",
        "outline-variant": "#4e4639",
        "surface-dim": "#131313",
        "on-tertiary": "#192f59",
        "on-secondary-container": "#342800",
        "surface-variant": "#353534",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        "container-max": "1440px",
        gutter: "32px",
        "margin-desktop": "64px",
        "section-gap": "128px",
        unit: "8px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontFamily: {
        sans: ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.15em", fontWeight: "600" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md-mobile": ["24px", { lineHeight: "1.3", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
